{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a36a54ec-0f41-4290-9181-6d9b4bd6cda5",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_2429/1959498649.py:34: DeprecationWarning: Argument login_or_token is deprecated, please use auth=github.Auth.Token(...) instead\n",
      "  g = Github(GITHUB_TOKEN)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🚀 Connecting to ArduPilot/ardupilot...\n",
      "   Searching for 'good first issue' (Limit: 50)...\n",
      "   [+] Found GFI: TemperatureSensor: Add Rangefi...\n",
      "   [+] Found GFI: Sub: add support for `WATER_DE...\n",
      "   [+] Found GFI: Add support for OPTICAL_FLOW_R...\n",
      "   [+] Found GFI: AP_Gripper: support HOLD comma...\n",
      "   [+] Found GFI: DO_SET_ROI_LOCATION and DO_SET...\n",
      "   [+] Found GFI: AP_Mount: mount_open servo out...\n",
      "   [+] Found GFI: EAHRS is performing duplicate ...\n",
      "   [+] Found GFI: AP_GPS_GSOF: Support GPS_RAW_D...\n",
      "   [+] Found GFI: Set Servo options triggered by...\n",
      "   [+] Found GFI: AP_DDS: Support IMU+gyro+accel...\n",
      "   [+] Found GFI: Remove mavlink enum dependenci...\n",
      "   [+] Found GFI: Custom Build Server Enhancemen...\n",
      "   [+] Found GFI: AP_SmartRTL algorithm breaks o...\n",
      "   [+] Found GFI: Write autotest for the no-shor...\n",
      "   [+] Found GFI: Make more features configurabl...\n",
      "   [+] Found GFI: Move test_onboard_logging_gene...\n",
      "   [+] Found GFI: Add visualisation for data in ...\n",
      "   [+] Found GFI: Modify autotest to notify Disc...\n",
      "   [+] Found GFI: Copter: POSITION_TARGET_LOCAL_...\n",
      "   [+] Found GFI: Copter: implement Circle withi...\n",
      "   [+] Found GFI: Make error more explicit on in...\n",
      "   [+] Found GFI: AP_Notify: Create automatic au...\n",
      "   [+] Found GFI: Plane: BUG with auto_state.che...\n",
      "   [+] Found GFI: Copter: pre-arm check \"Terrain...\n",
      "   [+] Found GFI: ADSB: _OFFSET_LAT, OFFSET_LON ...\n",
      "   [+] Found GFI: nmea output code should use fi...\n",
      "   [+] Found GFI: AC_Avoidance: Dijkstra's VisGr...\n",
      "   [+] Found GFI: Rover: boats entering SmartRTL...\n",
      "   [+] Found GFI: Rover: Guided mode's wp_bearin...\n",
      "   [+] Found GFI: SITL: add correct battery esti...\n",
      "   [+] Found GFI: RangeFinder: Using existing  A...\n",
      "   [+] Found GFI: PRX_ORIENT does not work (Tera...\n",
      "   [+] Found GFI: AP_Param can set parameters by...\n",
      "   [+] Found GFI: Rover: servo output range not ...\n",
      "   [+] Found GFI: SITL: AP_Camera object...\n",
      "   [+] Found GFI: Rover : Forward to waypoint # ...\n",
      "   [+] Found GFI: AP_RangeFinder: TerraRangeI2C ...\n",
      "   [+] Found GFI: Copter: add pre-arm check if f...\n",
      "   [+] Found GFI: Copter: vehicle may backup if ...\n",
      "   [+] Found GFI: SITL: reimplement the -P comma...\n",
      "   [+] Found GFI: Plane: Landing permanently dis...\n",
      "   [+] Found GFI: MAVlink library prevents OSD f...\n",
      "   [+] Found GFI: handle_mission_write_partial_l...\n",
      "   [+] Found GFI: Calibration messages come thro...\n",
      "   [+] Found GFI: Copter: add ch7 ch8 opt for se...\n",
      "   [+] Found GFI: Copter: easier test of benchte...\n",
      "   [+] Found GFI: Plane: make throttle slewrates...\n",
      "   [+] Found GFI: Copter: Pre-Arm Safety Check f...\n",
      "   [+] Found GFI: Copter: Activate buzzer when a...\n",
      "   [+] Found GFI: Copter: ensure visible (led) a...\n",
      "   Searching for 'complex' issues (Limit: 50)...\n",
      "   [-] Found Normal: DDS: Vehicle to report SITL st...\n",
      "   [-] Found Normal: `LOG_FILE_DSRMROT`: allow to w...\n",
      "   [-] Found Normal: Add support for the u-Blox ZED...\n",
      "   [-] Found Normal: DDS: External Odometry overflo...\n",
      "   [-] Found Normal: RTL_ALT_FINAL is relative to h...\n",
      "   [-] Found Normal: fix MAV_CMD_DO_START_MAG_CAL a...\n",
      "   [-] Found Normal: Ubuntu 24.04 ROS2 Jazzy build ...\n",
      "   [-] Found Normal: gimbal_device_id == 0 should c...\n",
      "   [-] Found Normal: Native Ship / Moving Platform ...\n",
      "   [-] Found Normal: Bosch BMP581 baro intermittent...\n",
      "   [-] Found Normal: speedybeef4v4  failed to initi...\n",
      "   [-] Found Normal: SIGFPE via incorrect type conv...\n",
      "   [-] Found Normal: SIGFPE via incorrect type conv...\n",
      "   [-] Found Normal: Provide a method to get a bina...\n",
      "   [-] Found Normal: scripting SRV_Channels:get_out...\n",
      "   [-] Found Normal: Drone fails to disarm in BRAKE...\n",
      "   [-] Found Normal: Python 3.9 EOL while search fo...\n",
      "   [-] Found Normal: DevEBox and WeAct Studio board...\n",
      "   [-] Found Normal: FPE in SITL...\n",
      "   [-] Found Normal: Unexpected Disarm in ACRO mode...\n",
      "   [-] Found Normal: Buffer overflow in ESP32 WiFi ...\n",
      "   [-] Found Normal: [SITL + ardupilot_gazebo] Iris...\n",
      "   [-] Found Normal: ESC to RPM sensor processing...\n",
      "   [-] Found Normal: Standard Modes Support problem...\n",
      "   [-] Found Normal: Add Units to PID parameters...\n",
      "   [-] Found Normal: Ensure Parameter metadata @Ran...\n",
      "   [-] Found Normal: Support MAVLink COMPONENT_META...\n",
      "   [-] Found Normal: Sub: 4.5 forward-port list...\n",
      "   [-] Found Normal: Copter SITL Webots-Python: iri...\n",
      "   [-] Found Normal: Copter: Dijkastras may get stu...\n",
      "   [-] Found Normal: AC_PrecLand LOCAL_FRD support ...\n",
      "   [-] Found Normal: sanity check for MAV_CMD_NAV_R...\n",
      "   [-] Found Normal: ALT_OFFSET error when commandi...\n",
      "   [-] Found Normal: AP_TemperatureSensor_MLX90614:...\n",
      "   [-] Found Normal: Feature request: Add Linux Min...\n",
      "   [-] Found Normal: AP_SCRIPTING: mavlink:send_cha...\n",
      "   [-] Found Normal: Support RTL_ALTITUDE when usin...\n",
      "   [-] Found Normal: Copter: Ch6 tuning of WP Speed...\n",
      "   [-] Found Normal: Copter parameter conversion fr...\n",
      "   [-] Found Normal: BDShot FW on IOMCU (F103) of n...\n",
      "   [-] Found Normal: ArduPilot doesn't start on som...\n",
      "   [-] Found Normal: STM32F412CGU6  bootloader USB ...\n",
      "   [-] Found Normal: No Parameter Length Validation...\n",
      "   [-] Found Normal: Leverage pending Ardupilot gim...\n",
      "   [-] Found Normal: Valgrind error in AP_Mission_C...\n",
      "   [-] Found Normal: After upgrading to arduplane 4...\n",
      "   [-] Found Normal: AP_DDS: add vicon pose informa...\n",
      "   [-] Found Normal: DSHOT issue with Ardu using 4i...\n",
      "   [-] Found Normal: DroneCAN Deadlock in dronecan_...\n",
      "   [-] Found Normal: AP_DDS: Servo Control...\n",
      "✅ Saved 100 issues to all_issues.csv\n",
      "🎉 Run Complete. Resting for 5 seconds...\n"
     ]
    }
   ],
   "source": [
    "import time\n",
    "import csv\n",
    "import os\n",
    "from github import Github\n",
    "from github.GithubException import RateLimitExceededException\n",
    "\n",
    "# --- CONFIGURATION ---\n",
    "GITHUB_TOKEN = \"\"  # Replace with your actual token\n",
    "OUTPUT_FILE = \"all_issues.csv\"\n",
    "TARGET_REPO = \"ArduPilot/ardupilot\"      # Change this for different runs!\n",
    "BATCH_SIZE = 50                          # We will fetch 50 Positive + 50 Negative = 100 Total\n",
    "\n",
    "def save_to_csv(issues_list):\n",
    "    \"\"\"Appends a list of issues to the CSV file.\"\"\"\n",
    "    file_exists = os.path.isfile(OUTPUT_FILE)\n",
    "    \n",
    "    with open(OUTPUT_FILE, mode='a', newline='', encoding='utf-8') as file:\n",
    "        writer = csv.writer(file)\n",
    "        # Write header only if the file is new\n",
    "        if not file_exists:\n",
    "            writer.writerow([\"repo\", \"title\", \"body\", \"labels\", \"is_beginner_friendly\"])\n",
    "        \n",
    "        for issue in issues_list:\n",
    "            writer.writerow([\n",
    "                issue['repo'],\n",
    "                issue['title'],\n",
    "                issue['body'],\n",
    "                issue['labels'],\n",
    "                issue['label_class']\n",
    "            ])\n",
    "    print(f\"✅ Saved {len(issues_list)} issues to {OUTPUT_FILE}\")\n",
    "\n",
    "def fetch_issues():\n",
    "    g = Github(GITHUB_TOKEN)\n",
    "    repo = g.get_repo(TARGET_REPO)\n",
    "    \n",
    "    collected_data = []\n",
    "    \n",
    "    print(f\"🚀 Connecting to {TARGET_REPO}...\")\n",
    "\n",
    "    # --- PART 1: Fetch POSITIVE Samples (Good First Issues) ---\n",
    "    print(f\"   Searching for 'good first issue' (Limit: {BATCH_SIZE})...\")\n",
    "    gfi_issues = repo.get_issues(state='open', labels=['good first issue'])\n",
    "    \n",
    "    count = 0\n",
    "    for issue in gfi_issues:\n",
    "        if count >= BATCH_SIZE: break\n",
    "        if issue.pull_request: continue # Skip PRs, we only want Issues\n",
    "\n",
    "        collected_data.append({\n",
    "            'repo': TARGET_REPO,\n",
    "            'title': issue.title,\n",
    "            'body': issue.body,\n",
    "            'labels': [l.name for l in issue.labels],\n",
    "            'label_class': 1  # 1 = Beginner Friendly\n",
    "        })\n",
    "        count += 1\n",
    "        print(f\"   [+] Found GFI: {issue.title[:30]}...\")\n",
    "    \n",
    "    time.sleep(2) # Safety Sleep\n",
    "\n",
    "    # --- PART 2: Fetch NEGATIVE Samples (Complex/Normal Issues) ---\n",
    "    # We purposefully exclude 'good first issue' label here\n",
    "    print(f\"   Searching for 'complex' issues (Limit: {BATCH_SIZE})...\")\n",
    "    normal_issues = repo.get_issues(state='open') # Gets everything\n",
    "    \n",
    "    count = 0\n",
    "    for issue in normal_issues:\n",
    "        if count >= BATCH_SIZE: break\n",
    "        if issue.pull_request: continue \n",
    "\n",
    "        # CRITICAL: Only add if it does NOT have the beginner label\n",
    "        current_labels = [l.name.lower() for l in issue.labels]\n",
    "        if 'good first issue' not in current_labels:\n",
    "            collected_data.append({\n",
    "                'repo': TARGET_REPO,\n",
    "                'title': issue.title,\n",
    "                'body': issue.body,\n",
    "                'labels': [l.name for l in issue.labels],\n",
    "                'label_class': 0  # 0 = Hard/Complex\n",
    "            })\n",
    "            count += 1\n",
    "            print(f\"   [-] Found Normal: {issue.title[:30]}...\")\n",
    "\n",
    "    # --- SAVE ---\n",
    "    save_to_csv(collected_data)\n",
    "    print(\"🎉 Run Complete. Resting for 5 seconds...\")\n",
    "    time.sleep(5)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    try:\n",
    "        fetch_issues()\n",
    "    except RateLimitExceededException:\n",
    "        print(\"❌ Rate Limit Hit! Waiting 60 seconds...\")\n",
    "        time.sleep(60)\n",
    "    except Exception as e:\n",
    "        print(f\"❌ Error: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "60e805a7-97ff-4b05-8871-3b22efce4fb5",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
